language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/bitly/go-simplejson
  - go get golang.org/x/net/publicsuffix

install:
  - go build

script:
  - go run examle/base.go
  # - $HOME/gopath/bin/goveralls -repotoken WAzmh3gmiQEUYEHM2wkwSH4oTrshvMmll

notifications:
  email:
    on_success: change
    on_failure: always
